### ISSUE TITLE
Does it work for Mac D2 1.14b

### ISSUE THREAD

**Issue by songpeng** [ChaosMarc/PlugY#1]
Hi, are you updating the PlugY yourself?
Can it now work on Mac D2 1.14b?
Songpeng

**Comment by LAutour** [comment]
Yes, I.
It wasn't necessary to deal with MacOS.
Support of patches 1.14 - it is still not ready.

**Comment by songpeng** [comment]
Hi,
1. Wasn't necessary means ?
a) If you update PlugY to 1.14, it can both be used in Windows and Mac.
b) PlugY only used in Windows, not for Mac.
Which one you are actually thinking of?
2.  It is quite different update 1.14 from 1.13 for PlugY ? BTW, if I want to try that for Mac, what's your suggestions?
Thanks a lot !

**Comment by LAutour** [comment]
PlugY is attached to a binary code of game. Therefore in Mac OS he will work only for windows of the version of game via the emulator (Wineskin).

I have finished PlugY under a patch 1.13d. In a patch 1.14 code have been considerably changed and on his analysis more time leaves.
