### ISSUE TITLE
SoJ's sold still needs to be greater than 75-125 when TriggerAtEachSOJSold is smaller.

### ISSUE THREAD

**Issue by BeefaloKing** [ChaosMarc/PlugY#11]
If the initial count is small, say 0, and the TriggerAtEach values are also small, say 1 and 2, you will still need to bring the count up to ~100 before the first dclone spawns. After that the custom TriggerAtEach values in PlugY.ini work as expected for future dclone spawns.

**Comment by ChaosMarc** [comment]
fixed by https://github.com/ChaosMarc/PlugY/releases/tag/v14.00
