### ISSUE TITLE
Downgraded to 1.13d, still PlugY doesn't work

### ISSUE THREAD

**Issue by drauch** [ChaosMarc/PlugY#12]
After I downgraded my 1.14b installation to 1.13d using the patch-zip from your web site, Diablo 2 won't start anymore (fails with an error message box without text in it - even tried to run in WinXP SP2 compat mode, no change)

If I try to start PlugY before running Diablo 2 I get the error:

> PlugY: Read process memory failed.

Any ideas? I'm running on Win10 64bit, everything en-US.

If it helps, my file layout is:

    D:\Games\Diablo II
    D:\Games\Diablo II\Mod PlugY
    D:\Games\Diablo II\PlugY
    D:\Games\Diablo II\support

I noticed that downgrading to 1.13d added many files to my Diablo II directory (lots of D2...dll files, also the exe files got much smaller - is that ok?)

Edit: same problem when downgrading to 1.13c

Edit2: I downloaded the game from my battle.net account, didn't install it from a CD. So it was immediately on 1.14b patch level (not 1.14d though, which seems to be the most up-to-date version)

**Comment by ChaosMarc** [comment]
Download my version changer from https://versionchanger.chaosmarc.de/ and run
`[8]   Fix 1.14 Installer MPQs (empty error window)`
if installed with the latest installers from blizzard (1.14b) the game is not downgradable out of the box and needs this fix. alternatively you can download the old 1.12 installer and start from there: https://mega.nz/#F!VIth1DKQ!Q42bVsCGQZ4UhoGjqvHxGw

**Comment by drauch** [comment]
Thanks for the quick and correct reply. Using your VersionChanger not only fixed my problem but it is also great for starting Diablo incl. PlugY. May I suggest one additional feature? Using PlugY reduced my FPS vastly, I had to install 3dfx-Glidewrapper from http://www.svenswrapper.de/english/ and set the (yet unknown to your VersionChanger) command line option "-3dfx". Optimally your VersionChanger would already include the newest version of 3dfx Glidewrapper and provide an option to add the -3dfx command line argument!

Thanks again for the quick reply and for keeping up the good work with this Plugin - love the big stash for single player mode! Finally I can start to collect Sets (which is near to impossible otherwise in single player).

**Comment by ChaosMarc** [comment]
I will think about it ;)
glad that I could help

**Comment by RandyGaul** [comment]
One important part - WinMPQ requires VB4 runtime, and RunPack3 (whatever that is, more VB stuff?). Info from ShadowFlare's site: http://sfsrealm.hopto.org/dwnload.html#WinMPQ
