### ISSUE TITLE
How to obtain knowledge like D2functions.cpp?

### ISSUE THREAD

**Issue by drauch** [ChaosMarc/PlugY#13]
Hi! I'm pretty intrigued by your tool and, a developer myself, got interested in how one can create such a mod. I stumbled upon D2functions.cpp - how on god's earth did you obtain that knowledge? Is there a modding guide out there? Which tooling did you use to obtain the initial knowledge on how to mod Diablo 2 features? Lots of assembler in there too...

Nice work guys!

**Comment by ChaosMarc** [comment]
Reverse Engineering with OllyDbg for almost everything. The [Phrozen Keep](https://d2mods.info) is a very good starting point
