### ISSUE TITLE
Playing w/o PlugY -> consequences?

### ISSUE THREAD

**Issue by drauch** [ChaosMarc/PlugY#14]
Hi!

What happens if, after extensively using the extended stash, I decide to play without PlugY (e.g., do play with my brother via Open-BattleNet). What happens if my character is safed? Am I losing all the items of the extended stash? Or are they simply not accessible and when I turn PlugY back on in a single player session, the stash and all its content is back?

Best regards,
D.R.

**Comment by ChaosMarc** [comment]
Both the PlugY shared and your personal stashes are safe. The non-plugy stash (Vanilla 6x8) though is not. 

This is the one way you can loose items:
1. Play with PlugY and put stuff into your first personal stash page
2. Disable PlugY. Now you have a copy of the upper left 6x8 inventory fields of PlugY's first personal page. 
3. Enable PlugY. The first personal PlugY stash page will be used as it was before you disabled PlugY.
	1. All items you've moved from your stash to your character while playing without PlugY will be **duplicated**.
	2. All items you've put into the Vanilla stash while playing without PlugY will be **lost forever**.

So the easiest way to not loose items when switching between Vanilla and PlugY
