### ISSUE TITLE
Contribution and Documentation

### ISSUE THREAD

**Issue by BrianArne** [ChaosMarc/PlugY#16]
Is there any additional documentation or contribution guidelines? I'm interested in the project and looking for a little more information.

**Comment by ChaosMarc** [comment]
sadly no. There is only the source code @YohannNicolas uploaded to his homepage http://plugy.free.fr
I just created a repo from it.
as for contribution. you are free to help out in any way you can. there are some minor issues that have to be verified and fixed after that like #15 or #11 
as a big task there is the compatibility update for 1.14 of course. @LAutour started working on it but has stopped I think. His progress can be found in the branch "1.14": https://github.com/ChaosMarc/PlugY/tree/1.14 
If you are able to, you can start working on that too :)

I will close this in a few days, as it is not really an "issue"
