### ISSUE TITLE
[Request] Stash Text Color

### ISSUE THREAD

**Issue by conetopia** [ChaosMarc/PlugY#17]
![untitled](https://user-images.githubusercontent.com/4310295/47686138-a8094000-dba7-11e8-81ee-cf557a1d7865.png)
As you can see here with plugy 11.02
Grey Personal & Red Shared stash tabs.
Is there any way to change the color of text?
an example would be 
Shared Page n"1  ( in green ) instead of red.
maybe like a new command for this? or a way to add color codes?
/renamepage Shared Page n"1 {Color=green} or something ?
/recolorpage Green,blue , ect

Edit: note
Not sure if it makes the giant difference or not, But Playing Eastern sun rises 5.1H mod.
Using Diablo 2 LoD Core 1.10F

**Comment by ChaosMarc** [comment]
You can achieve different colors for ALL personal/shared pages by simply editing the LocalizedStrings.ini in the PlugY folder.

just add one of the following color codes in front of a translation and you're good to go:
ÿc1 = Red
ÿc2 = Blue
ÿc3 = Green
ÿc4 = Gold
ÿc8 = Orange
ÿc- = White
ÿc: = Dark Green
ÿc0 = white
ÿc5 = grey
ÿc6 = black
ÿc7 = gold
ÿc9 = Yellow
ÿc; = Purple

e.g.
```
[STR_PERSONAL_PAGE_NUMBER]
ENG=ÿc3Personal Page n°%u

[STR_SHARED_PAGE_NUMBER]
ENG=ÿc8Shared Page n°%u
```

a new command for renaming individual pages would require some work ;)

**Comment by conetopia** [comment]
Oh nice, alright thank you !
