### ISSUE TITLE
Read Process Memory Failed

### ISSUE THREAD

**Issue by chrisheseltine** [ChaosMarc/PlugY#20]
I am getting this error since yesterday when I try to start PlugY. Nothing changed between the time it was working and now, other than I switched my PC off.

This errors sometimes occurred for me before but trying to open the .exe again always worked. I have tried a completely fresh install of D2 and PlugY multiple times and I cannot get this working.

More details:
1. I have tried compatibility mode (wasn't needed before but tried it anyway)
2. D2 vid test doesn't run so I thought it was a graphics issues however I run it the game with the launch param "-w" as a standard procedure, and when I launch D2 (without PlugY) it works fine
3. I have tried using D2SE to ensure that the version and files of D2 match was PlugY is expecting, but that also doesn't work (D2SE crashes with no error)
4. I have tried Sven's Glide wrapper

Any help you can give would be appreciated, I am a developer myself, and it seems strange to me that this would suddenly stop working with no system changes AND still not work after a fresh install. I would guess it has something to do with some system process being locked that PlugY needs?

Thanks.

**Comment by ChaosMarc** [comment]
Something like this could be caused bei ASLR (https://en.wikipedia.org/wiki/Address_space_layout_randomization) errors. The only "fix" that can be applied without updating the source is restarting your computer until it works again.

**Comment by chrisheseltine** [comment]
But I restarted many times and it does not work. So I cannot play anymore? :(

Restoring my PC is not really an option as it would take me about a week to build the software stack again and I need all that for work...

**Comment by chrisheseltine** [comment]
I just tried using an older version (10.0.0) and now the error is different:
"Checking library memory check failed"

Does this shed any more light on the issue?

**Comment by ChaosMarc** [comment]
I would suggest the following steps:
- deinstall diablo
- remove the complete folder (backup saves)
- clean windows registry (search for diablo)
- restart
- install diablo + lod
- if the 1.14er digital installers were used, download [my versionchanger](https://versionchanger.chaosmarc.de/) and fix the mpqs
- install d2se
- set compatibility mode (WinXP SP3) for D2SE.exe, Diablo II.exe and Game.exe
- (optional) upgrade D2SE's PlugY by extracting all files from plugy's zip file FLAT (all files from the "plugy" sub-directory in the zip go to the same level as the plugy.dll, so that there is no "Diablo II\PlugY\PlugY\ folder") to "Diablo II\PlugY\" and overwrite everything
- run d2se and start the version you like with plugy

**Comment by chrisheseltine** [comment]
I will try and let you know, thanks

**Comment by chrisheseltine** [comment]
I used the digital installers and followed your instructions. However I had no success with the version changer, it says if you used the digital installers then to use MPQFix.exe but that errors with "Error accessing the system registry".

If I try D2SE with PlugY I get "This application has encountered a critical error: the file data is corrupt" and it mentions "D2SE.exe" and "d2data.mpq". Do you have any other suggestions?

I will try with the old installers linked from the versionchanger site...

**Comment by chrisheseltine** [comment]
Using the classic installers seems to work (D2SE comes bundled with PlugY 10.0.0 which is working for me).

Thanks for your help. Anyone else facing this issue can use the classic installers linked above in the version changer website and then use PlugY bundled with D2SE. I patched it using the official patcher to 1.13d.

**Comment by ChaosMarc** [comment]
@chrisheseltine just curious. did you try to run the MPQFix.exe manually? If you start the versionchanger there is a option to execute it with the correct commands to fix the mpqs. do you get the "Error accessing the system registry". in this case too? is your diablo installed to C:\Program Files (x86)\ ?

**Comment by chrisheseltine** [comment]
Yeah I did, I didn't realize I was supposed to start the version changer to access it. Perhaps you could update the instructions to be a little clearer (atm is just says use the included MPQFix which to me means MPQFix.exe)?

I didn't actually try it this way in the end so I can't say if it would have worked, sorry, I already deleted that version.

I did however get PlugY bundled with D2SE working with the old installers linked on the versionchanger site, so that's good news. However I forgot to save my shared stash file, and only kept my chars, so I lost my nice "museum" stash that I had going, nevermind!

Thanks for the follow-up, I appreciate the level of support.

**Comment by ChaosMarc** [comment]
> Perhaps you could update the instructions to be a little clearer (atm is just says use the included MPQFix which to me means MPQFix.exe)?

I just did that. Thanks for the feedback

**Comment by Xiantrius** [comment]
I have same problem and can not start PlugY
My System:
Windows 10 Pro

Mainboard:
ASUS B550-F Gaming ROG Strix

CPU:
AMD Ryzen 9 5950X

Grafic Card:
Radeon RX 6700X

RAM:
128 GB DDR4 RAM

![2022-08-27 12_51_11-PlugY](https://user-images.githubusercontent.com/42416073/187039649-bb27cbaa-083f-4369-8199-f1edb637e9c3.png)

1. First i try new installation from Diablo 2 Expansion v1.14D

2. Restart PC

3. I downgrade Diablo 2  Expansion v1.14 to v1.13x

4. New Install Plugy.

5. Try Start PlugY without other Mods.

i hope come fix for PlugY.
