### ISSUE TITLE
when you open 2 plugys, then create 2 characters and link by local net, plugy will crash

### ISSUE THREAD

**Issue by lishaoxia1985** [ChaosMarc/PlugY#24]
by the way, I hope plugy runs without installing visual c++ 2015 redistributable.
You can statically compile this app.

**Comment by lishaoxia1985** [comment]
It runs well in haxfix's compiled branch.
by the way, I hope plugy runs without installing visual c++ 2015 redistributable

**Comment by ChaosMarc** [comment]
This is caused by the shared stash. if you disable the feature completely (ActiveSharedStash=0) you can play with multiple chars on local network.

Actually I'm happy that I got it to compile at all :D It's been ages since I meddled with C++ / Visual Studio. Can you tell if it is compiled statically at the moment?

**Comment by lishaoxia1985** [comment]
@ChaosMarc 
about crash problem,  I will try it as you said.
about static link,  you can watch this website:
https://helloacm.com/how-to-static-link-vc-runtime-in-visual-c/

**Comment by ChaosMarc** [comment]
Thank you for the link. I will look into it

**Comment by lishaoxia1985** [comment]
I have a suggestion:
when you play with multiple chars on your local network, the sharedstash button is disabled automatically and gives some message "this button is disabled because you play the game on local work", and the default value of ActiveSharedStash is 1.
this doesn't need to edit more code.
how do you think?

**Comment by ChaosMarc** [comment]
Sounds easier to implement for sure. As I'm no c++ developer this something that would take me longer that a few minutes.
I just tested it again. you need to disable the whole multi-page-feature as well (ActiveMultiPageStash=0)

**Comment by lishaoxia1985** [comment]
@ChaosMarc now it cannot reassign skill point. The haxifix brach runs well.😁

**Comment by ChaosMarc** [comment]
@lishaoxia1985 I can use the skill unassign button regardless of the settings for ActiveSharedStash and ActiveMultiPageStash. Did you do something else? If this is a general problem for you it would be better to open a new issue. What version are you playing (or mod).
