### ISSUE TITLE
Crash when freeing custom libraries

### ISSUE THREAD

**Issue by Snapchip** [ChaosMarc/PlugY#27]
Related issue: https://github.com/haxifix/PlugY/issues/4

The crash doesn't happen just with BaseMod, it also happens if you load a dll that does nothing.

Crash caused by:
https://github.com/ChaosMarc/PlugY/blob/e0472480c48143e87836114bfcacb79862356329/PlugY/D2wrapper.cpp#L234

**Comment by markm11** [comment]
All this function does is allocate memory for a string.   There are other ways to do this.   I am looking into this.

**Comment by ChaosMarc** [comment]
fixed by https://github.com/ChaosMarc/PlugY/pull/31
