### ISSUE TITLE
Support 1.14

### ISSUE THREAD

**Issue by KornelJahn** [ChaosMarc/PlugY#3]
Thanks for updating PlugY to support 1.13d. Any plans on supporting 1.14?

Update: I have noticed that work is in progress.

**Comment by LAutour** [comment]
> Any plans on supporting 1.14?
Yes

**Comment by SilverSix311** [comment]
Any news on this?

**Comment by LAutour** [comment]
work, work, work :(

**Comment by Harest** [comment]
Just started to play Diablo 2 some days ago and i now know the mod MrLlamaSC is using to have this infinite stash (only option i'm interesting in) is this one, PlugY. Crazy there's not a damn thing on the authors of this mod on the official "site" (or should i say page). I saw a "Yohann" in a wiki and that's all.  

Just wanted to know what was the compatibility issues of the mod with the latest version of D2 LOD ? Even if i'll probably not be able to help :/.

**Comment by ChaosMarc** [comment]
@LAutour 
Yohann released another update (11.02) which collides with your changes.
Could you please redo/copy your preparations for 1.14 into a **separate branch** as the changes are major and shouldn't be commited to the master branch.
For the time being I created a branch 11.02 which is exactly Yohann's code without any changes by the community.

**Comment by drauch** [comment]
Is there any work ongoing or has the idea of a port to 1.14 been abandoned?

**Comment by ChaosMarc** [comment]
I cleaned up the branches a bit. Master now is the latest official version by Yohann (11.02) with the translation fixes previously done in this repo.
LAutour's 1.14 Code can be found in a separate branch called "1.14"

no actual progress toward a 1.14 compatible version has been done by me!

**Comment by manu666fr** [comment]
Hi guys,
Thank's for your great work.
@LAutour are you working on an 1.14 version still or have you abandoned the project?
byebye ;-)

**Comment by hossomi** [comment]
Is there any... thing I can read to help understand and contribute to this?

**Comment by stonecrusher** [comment]
@hossomi Maybe this [thread](https://d2mods.info/forum/viewtopic.php?p=481047#p481047) / forum is helpful?

**Comment by ChaosMarc** [comment]
@stonecrusher is correct. In general the [Phrozen Keep](https://d2mods.info), especially the [PlugY](https://d2mods.info/forum/viewforum.php?f=133) and [Code Editing](https://d2mods.info/forum/viewforum.php?f=8) section are good starting points.

**Comment by Gragog** [comment]
Any news on this? I couldn't run any 1.13 version on my PC (crash on start with `ACCESS_VIOLATION (c00000005) EXCEPTION`). I would be happy to use this mod.

**Comment by ChaosMarc** [comment]
@Gragog If you're having problems running plugy with 1.13 please create a new ticket but I think a full removal of diablo II and a clean install will fix your problems.

For your actual question: I just found out that there is a new version of plugy which supports 1.14d. I'm trying to contact the creator so we can merge both repositories: https://github.com/haxifix/PlugY

**Comment by ChaosMarc** [comment]
I finally found the time and merged the two code bases. I have created a new release with all credits to https://github.com/haxifix: https://github.com/ChaosMarc/PlugY/releases/tag/12.00

**Comment by drauch** [comment]
So nice! I see that you're also closing lots of bugs so probably another minor step upcoming? : )

Do you know that Windows Defender detects PlugY 12 as a trojan horse?

Best regards,
D.R.

**Comment by ChaosMarc** [comment]
@markm11 told me he was working on a fix for https://github.com/haxifix/PlugY/issues/12. I'm waiting for that and will release v12.01 afterward

regarding the "trojan horse". I didn't know that. thanks for the info. I will look into that

**Comment by drauch** [comment]
Windows Smart Screen and heuristic detection algorithms of the Windows Defender may be to blame. Oftentimes this goes away after enough users have installed the new version (or after you have code-signed your software, but that's probably not an option for you because of the certificate costs).
