### ISSUE TITLE
Only load shared stash on demand

### ISSUE THREAD

**Issue by oskros** [ChaosMarc/PlugY#32]
I dont know if it is possible, but would be a huge QoL feature if the shared stash was only loaded when the player tried to access it, to help improving the character load times (could be optional from settings)

**Comment by ChaosMarc** [comment]
I hadn't noticed any overlong loading times, but I will do some tests regarding this. Don't know if this can be done easily

**Comment by ChaosMarc** [comment]
fixed with https://github.com/ChaosMarc/PlugY/releases/tag/v14.00
