### ISSUE TITLE
About Nilathek Portal

### ISSUE THREAD

**Issue by whybm** [ChaosMarc/PlugY#38]
PlugY .ini should increase “ActiveDoNotCloseNihlathakPortal=1” at the end

It was originally in haxifix‘s PlugY.ini

**Comment by ChaosMarc** [comment]
I tested the feature in the past and it didn't work for me. I will play around with it some more and add it to PlugY.ini if it's working

**Comment by whybm** [comment]
I just re installed 1.14d，and use PlugY.exe to enter  the  game.
“ActiveDoNotCloseNihlathakPortal=1”  is working in PlugY.ini
