### ISSUE TITLE
/page4 feature crash

### ISSUE THREAD

**Issue by whybm** [ChaosMarc/PlugY#39]
The same problem in
https://github.com/haxifix/PlugY/issues/11#issue-670355327

When I open the character page, and enter the command /page4, the game crashes. 
It's running well  with 11.02 in 1.13d

**Comment by ChaosMarc** [comment]
Works fine on my machine (tested with plugy 12 and 1.13c + 1.14d). can you please attach the latest log files (plugy + blizzarderror folder)? are you using additional mods/hacks/tools?

**Comment by whybm** [comment]
I just re installed 1.14d English ver   at win10 20H2
，and use PlugY.exe to enter  the  game, no other mods.
 the game crashes, when   enter the command /page4 
I has post crash.txt in blizzarderror folder
[Crash.txt](https://github.com/ChaosMarc/PlugY/files/5623229/Crash.txt)

**Comment by whybm** [comment]
Just find " -direct"  is  not working

**Comment by ChaosMarc** [comment]
-direct was fixed in https://github.com/ChaosMarc/PlugY/pull/34 and will be included in the next release.

there should be a plugy.log file somewhere. could you please upload this as well?

**Comment by whybm** [comment]
[PlugY.log](https://github.com/ChaosMarc/PlugY/files/5623680/PlugY.log)
 I didn't find any error message in it

**Comment by ChaosMarc** [comment]
what is the error message exactly? c00000005? if thats the case could you please try and restart your PC a couple of times (at least 5 for a large enough amount of test results) and try the "/page 4" command in between each restart?

**Comment by whybm** [comment]
I just test again on win7 desktopPC. 
My game is downloaded from Blizzard Shop.
/page4 feature run well in 1.13d,  and  crash  in 1.14d, 
Several attempts were made after restarting the computer.

**Comment by markm11** [comment]
Can you show me what in your statsinterface.txt file?  This will help when trying to duplicate it since you should have page 3 in there.

**Comment by whybm** [comment]
I didn't change statsinterface.txt
[statsinterface.txt](https://github.com/ChaosMarc/PlugY/files/5630111/statsinterface.txt)
page2 and 3 work well

**Comment by whybm** [comment]
I download PlugY 12 from ChaosMarc's release.
/page4 feature run well in 1.13d, and crash in 1.14d.  page2 and 3 work well
turn on ActiveLogFile=1 
[PlugY.log](https://github.com/ChaosMarc/PlugY/files/5630553/PlugY.log)
Minidump.dmp raname Minidump.txt
[Minidump.txt](https://github.com/ChaosMarc/PlugY/files/5630570/Minidump.txt)

**Comment by ChaosMarc** [comment]
How are you changing between versions? which video mode are you using?

**Comment by whybm** [comment]
> How are you changing between versions? which video mode are you using?

I reinatalled  Blizzard Shop Ver 1.12,and  run "LODPatch_114d.exe", /page4 feature crash.
Then I delete all files ,reinatalled  Blizzard Shop Ver 1.12,and  run "LODPatch_113d.exe", /page4 work well.
All test run in "-w" ddraw mode

**Comment by markm11** [comment]
I wonder if anyone out there can build the source on (Simplified Chinese) and debug the plugy.dll to see where to crash is at.  I looked at your minidump and see that your crash was at 0x0068F2D.  If I debug the plugy.dll and put a breakpoint on that address it get called all the time and I do not see plugy.dll calling it.

**Comment by whybm** [comment]
> I wonder if anyone out there can build the source on (Simplified Chinese) and debug the plugy.dll to see where to crash is at. I looked at your minidump and see that your crash was at 0x0068F2D. If I debug the plugy.dll and put a breakpoint on that address it get called all the time and I do not see plugy.dll calling it.

Sorry，I don't have the ability. If it's not a common problem, just  ignore it

**Comment by jc3213** [comment]
I also have `/page 4` crash and altogether with `/swap xxxx` crash

Here's PlugY.log and Crash.txt on `/plage 4` crash
[Crash.txt](https://github.com/ChaosMarc/PlugY/files/5718894/Crash.txt)
[PlugY_page_4.log](https://github.com/ChaosMarc/PlugY/files/5718895/PlugY_page_4.log)

Here's PlugY.log and Crash.txt on `/swap 1200` crash
[Crash.txt](https://github.com/ChaosMarc/PlugY/files/5718898/Crash.txt)
[PlugY_swap1200.log](https://github.com/ChaosMarc/PlugY/files/5718899/PlugY_swap1200.log)

**Comment by markm11** [comment]
The /swap 1200 crash can be duplicated and I have a fixed it.  Still cannot duplicate /page 4 crash.

**Comment by jc3213** [comment]
I've tried use version change from https://github.com/ChaosMarc/D2VersionChanger , and official PlugY 11.02.

The game still crashes on 1.13c with the latest unofficial PlugY 12.0 from ChaosMarc and haxifix, when using `swap 1200` and `/page 4`.

If I downgrade to PlugY 11.02 from Yohann `/page 4` works correctly but only on 800x600 resolution.
[PlugY.log](https://github.com/ChaosMarc/PlugY/files/5719125/PlugY.log)
![page 4](https://user-images.githubusercontent.com/8744936/102685998-953aa500-421f-11eb-8722-e2119cb7516c.png)

But `/swap 1200` still crashes even with official PlugY 11.02
![swap 1200](https://user-images.githubusercontent.com/8744936/102686037-da5ed700-421f-11eb-8162-6b72e640e75d.png)

Here's crashdump and d2log
[D2201219.txt](https://github.com/ChaosMarc/PlugY/files/5719145/D2201219.txt)
[Crashdump.zip](https://github.com/ChaosMarc/PlugY/files/5719147/Crashdump.zip)

**Comment by markm11** [comment]
Yes the /swap issue existed in plugy 11.02

Can you upload your "statsinterface.txt" in the Plugy directory.

**Comment by jc3213** [comment]
This one is from Diablo II LoD 1.13c and official PlugY 11.02
[statsinterface.txt](https://github.com/ChaosMarc/PlugY/files/5719158/statsinterface.txt)

**Comment by whybm** [comment]
> This one is from Diablo II LoD 1.13c and official PlugY 11.02
> [statsinterface.txt](https://github.com/ChaosMarc/PlugY/files/5719158/statsinterface.txt)

What language is your operating system?@jc3213
/page4 feature run well in 1.13d  with  plugy12  on  my  pc

**Comment by jc3213** [comment]
It's `en-US`, other specifications are: Core i5-4460, 16GB DDR3 1866RAM, 64bit OS, GTX 1060 6GB,

There are no other mods, no 3rd-party tools (such as Hi-res)

Here's the whole crash folder contents

[2020-12-19 18.34.02.zip](https://github.com/ChaosMarc/PlugY/files/5719207/2020-12-19.18.34.02.zip)

**Comment by markm11** [comment]
Thanks for point out that when you run a resolution with 800x600 /page works.   Now I can duplicate the /page crash.   Now to see how to fix it.

**Comment by markm11** [comment]
Found the problem.   When @haxifix was updating plugy for version 114d he missed updating this code for the /page 4 option.

```
F8(STD,  D2Common,10619,10619,10619,10687,10877,10321,11032,**10981, 10981**, int*,		D2GetNbRunesBIN, ());//return the point on th number
F8(STD,  D2Common,10620,10620,10620,10775,10296,10622,10006,**10405, 10405**, RunesBIN*,	D2GetRunesBIN, (int runesID));
```
The D2GetNBRunesBIN and D2GetRunesBIN functions have the same adddress as 113d.  This should not be the case in 114d because all the function are now in Game.exe.   I started to look into Game.exe to see what address to use but I am wondering if anyone else would know what address to use for these functions.   This might take me sometime to figure it out.

**Comment by ChaosMarc** [comment]
in my opinion the best place to find this kind of information would be the phrozen keep or their discord.

**Comment by markm11** [comment]
I fixed those and found what address to use.  Now having the same issue with D2GetGemsBIN and have to find what address to use for it.

**Comment by markm11** [comment]
![image](https://user-images.githubusercontent.com/6216490/102713266-fe103480-4294-11eb-9c38-acc73e021edb.png)

Got some of it working for /page 4.  Still working  on why it does not fill up entire screen like in previous versions.
