### ISSUE TITLE
ActiveSavePathChange not compatible with NBPlayersByDefault on 1.14d with PlugY 12.00 (ChaosMarc)

### ISSUE THREAD

**Issue by jc3213** [ChaosMarc/PlugY#40]
Since D2LoD 1.14 has changed save folder to `Saved Games` folder under user document, I'd like to change it back to Game installation folder where old versions do. `ActiveSavePathChange=1`

I've tried `haxifix`'s unofficial release, it do changed the save folder, but after I copy back my save datas, the game crashes every time when I click on `Single Player` on main menu.

Then I tried `ChaosMarc`'s (This repository), it won't crash but `NBPlayersByDefault` -> which is `/players X` on start up seems have problem with this option and shows weird message as this screenshot
![weird](https://user-images.githubusercontent.com/8744936/102686939-2ad93300-4226-11eb-96e1-88ba6b41d2c5.png)

If I disable the option by setting `ActiveSavePathChange` to `0`, the start up `/players X` provided by `NBPlayersByDefault` works fine
![normal](https://user-images.githubusercontent.com/8744936/102686955-4e03e280-4226-11eb-9120-ba56a32c0279.png)

**Comment by whybm** [comment]
I met it in a different situation
If I  exit and save the game，then quickly re-enter the game，this weird message will appear.
If  I entered the game again in a few seconds，It never appeared again.

**Comment by ChaosMarc** [comment]
fixed with https://github.com/ChaosMarc/PlugY/releases/tag/v14.00
