### ISSUE TITLE
Crash after clicking "Unassign all skills points"

### ISSUE THREAD

**Issue by KarolWojtasiuk** [ChaosMarc/PlugY#41]
## Description
The game crashes after clicking the button but only when there are skills to unassign. Unassigning stats points works.

## How to reproduce
1. Install D2LOD 1.14d
2. Install PlugY 12.00
3. Run and create new character
4. Level up character
5. Assign skill
6. Click button `Unassign all skills points`

## Game information
Game Version: 1.14d
PlugY Version: 12.00

## Machine information
OS: Linux 5.9.14-arch1-1
Wine: 5.22

## Logs
[stdout](https://pastebin.com/cSareAus)
[Crash.txt](https://pastebin.com/EDrWnWWx)
[D2201220.txt](https://pastebin.com/JZMQc6V3)
[PlugY.log](https://pastebin.com/cqcz0NgY)
[PlugY.ini](https://pastebin.com/UBZsEPca)

**Comment by markm11** [comment]
Did you try this repack version?
https://github.com/ChaosMarc/PlugY/releases/tag/12.00

**Comment by KarolWojtasiuk** [comment]
Yeah, I downloaded PlugY from this link.

Btw. I tried a few different install methods:
* .exe installer
* .zip manual install
* .zip manual install + PatchD2File.exe

Error occurs every time.

**Comment by markm11** [comment]
Well you are right.  @ChaosMarc must have not put my fix in those in that repack version.   I downloaded the .zip manual install and sure enough it crashed.   I then took my plugy.dll that has the fix in it and no crash.   Here is my pull request to him.
https://github.com/ChaosMarc/PlugY/pull/30

**Comment by ChaosMarc** [comment]
Sorry I'm swamped with work atm. I will release a new version with all of mark's fixes some time between Christmas and new year's eve

**Comment by KarolWojtasiuk** [comment]
@markm11 Can you upload somewhere PlugY.dll with fixes? I don't have Windows PC and I can't build lib.

**Comment by markm11** [comment]
Sure.  It wont be till around 9:00 pm GMT.   I have to get to work soon.

**Comment by markm11** [comment]
[PlugY.txt](https://github.com/ChaosMarc/PlugY/files/5726306/PlugY.txt)
Download this file and rename it to Plug.dll

**Comment by KarolWojtasiuk** [comment]
Ok, now it works. Thanks for help.
