### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Goatflakes** [ChaosMarc/PlugY#45]
I'm wondering how to compile this, as there isn't a precompiled version (yet). I have Visual Studio Community Edition 2017. I don't see a project file, just several solution files. Thanks.

**Comment by ChaosMarc** [comment]
Why would you say there is no precompiled version? There are plenty: https://github.com/ChaosMarc/PlugY/releases

And compiling should be easy: open Plugy.sln with Visual Studio, select "Build" -> "Build PlugY". After that PlugY.dll should be in your Release/Debug directory. For PlugY.exe order PatchD2File.exe check PlugYInstall and PlugYRun.

**Comment by Goatflakes** [comment]
Thanks for that. My brain was obviously not fully engaged before leaving the kerb. Though might I suggest adding a link to the released in the Readme?
