### ISSUE TITLE
Multires problem

### ISSUE THREAD

**Issue by ranafuineluva** [ChaosMarc/PlugY#47]
Hi guys,

I have a problem with multires integration. When I edit plugy.ini as like this:
[GENERAL]
ActivePlugin=1
DisableBattleNet=1
ActiveLogFile=0
DllToLoad=D2MultiRes.dlls
DllToLoad2=
ActiveCommands=1
ActiveCheckMemory=1

Plugy stops working. Can you please integrate what multires does into plugy installer as anoption please?

**Comment by ChaosMarc** [comment]
1. you have to give some more information. which version of d2, plugy and d2multires are you using? I guess your dll isn't really named D2MultiRes.dll**S** so the configuration above would be wrong. 
2. Please be more precise. "Plugy stops working" doesn't help at all. what's happening? do you get an error on startup / character loading / midgame? 
3. PlugY will never include an MultiRes option

**Comment by ranafuineluva** [comment]
1- D II is LoD 1.13. , MultiRes 1.13c, plugy is the newest version.
2- When I press the PlugY, The Survival Kit shortcut, the games fails to load. No error messages. Just the main menu does not load.
3- I was asking if you could add multires  function to plugy installer for a future version.

**Comment by ChaosMarc** [comment]
just to be sure: does the name of the dll exactly matches what you put into the "DllToLoad=" line? in the code above you have a 'S' at after 'D2MultiRes.dll' which could be the problem. Does plugy start correctly if you leave "DllToLoad=" emtpy?

**Comment by ranafuineluva** [comment]
Yes, when I make empty that line and make it 
DllToLoad= 
It works.
I corrected the extra s.
[GENERAL]
ActivePlugin=1
DisableBattleNet=1
ActiveLogFile=0
DllToLoad=D2MultiRes.dll
DllToLoad2=
ActiveCommands=1
ActiveCheckMemory=1

No change.

**Comment by ranafuineluva** [comment]
Here is a screenshot of my DII game folder showing files that can be related to Plugy.
https://drive.google.com/drive/folders/1K7rgxiL1VZ2lonL9pjyg_uQXXleCrDpg?usp=sharing

The shortcut plugy.exe is default. Doesn't have any compatibility or any kind of running parameters.

**Comment by ChaosMarc** [comment]
Can you please delete plugy.log, start the game and upload the newly created plugy.log? 
Did you copy the D2MultiRes.mpq to your D2 directory too?
I guess you're using this MultiRes Plugin, but just to be sure I attached the one I'm using which is working fine: [D2MultiRes-v102 (1.13c).zip](https://github.com/ChaosMarc/PlugY/files/6383407/D2MultiRes-v102.1.13c.zip)

**Comment by ranafuineluva** [comment]
I replaced your multires file with my one. And I uploaded plugy.log to my google drive folder .

https://drive.google.com/drive/folders/1K7rgxiL1VZ2lonL9pjyg_uQXXleCrDpg?usp=sharing

**Comment by ranafuineluva** [comment]
Hi
I replaced my old multires file with yours.
And deleted plugy.log and uploaded the new one to my google drive folder.
https://drive.google.com/drive/folders/1K7rgxiL1VZ2lonL9pjyg_uQXXleCrDpg?usp=sharing

**Comment by ChaosMarc** [comment]
Are you sure that your config matches the name of the dll? In the log I can see you've configured D2MultiRes_113c.dll. That should match the dll from my zip. Are you running with admin privileges?

**Comment by ranafuineluva** [comment]
awds

**Comment by ranafuineluva** [comment]
Tried it with admin.

**Comment by ChaosMarc** [comment]
The log says you're using 1.13d. D2MultiRes is only for 1.13c. can you please downgrade (e.g. with my version-changer https://github.com/ChaosMarc/D2VersionChanger) and try again?

**Comment by ranafuineluva** [comment]
I am gonna cry. It worked. :D

**Comment by ChaosMarc** [comment]
Glad I could help :)
