### ISSUE TITLE
plugy.exe alert an read memory error when game.exe patched with PatchD2File.exe

### ISSUE THREAD

**Issue by 3594302** [ChaosMarc/PlugY#48]
D2x  updated to ver 1.14d with official Lodpatch.exe, chinese-t, windows 10 pro, only plugY 14.02 copied in game folder.

if game.exe be kept in unpatched status, it could start game with plugy.exe, and plugy function worked well, whatever game.exe is restored from patched status or never patched.
but once the game.exe patched with PatchD2File.exe, it plugy.exe started will alert an read memory error instead of building the game window.  while the plugy function worked actually in game if start directly with game.exe/diablo II.exe -w.  
is this a bug or not ?

I did not load any dll file in plugY.ini.

**Comment by ChaosMarc** [comment]
This ist exactly the intended feature. PatchD2File.exe and PlugY.exe are two independent methods of starting D2 with PlugY. Either just start PlugY.exe or run PatchD2File.exe ONCE and start Game/Diablo II.exe afterwards. You cannot combine both
