### ISSUE TITLE
Custom Font Fix

### ISSUE THREAD

**Issue by DerWeedologe** [ChaosMarc/PlugY#5]
Hi there, i found a bunch of different font fixes for diablo.

[Custom Font 1](https://median-xl.com/tools_files/D2_Custom_font.zip)
[Custom Font 2](http://www98.zippyshare.com/v/5JOG0pch/file.html)

The first font fix has a modified Plugy.dll in it. But i dont rly know what is changed. 

I thought maybe we could implement a fix. Bcause game is crashing when opening stash, while using a modified diablo2  font.

**Comment by LAutour** [comment]
It is a problem not of Plugy, and the truncated user fonts where there is no character '°'
It is possible to correct editing of PlugyLocal.ini  with changeover of all characters of '°' by 'o', but then simulation of the character '№' will be gone in a game (n° -> no)

**Comment by DerWeedologe** [comment]
Ah yes, i know what you mean.

You ment the degree mark, for example in ESP="Page perso n°%u"

when we ad some Unicode like ASCII (ALT+0167) for degree mark? But when only ANSI support... idk.

**Comment by DerWeedologe** [comment]
What when we compile another version, for custom font using. ?

**Comment by LAutour** [comment]
PlugyLocal.ini - is an external text file of localization, it doesn't compile to anything. It is available to editing always.
But anyway - a problem in the user font. If there was a laziness to add the character of '°', then why it was impossible to correct in the table of characters its index of a figure on an index of a figure 'o'?

**Comment by DerWeedologe** [comment]
Yeah, i figured out, that he changed the character '°' to "o".
 
But, why is it so necessary? The rigth shortcur grammar for "Number" is "No.". 

So my suggestion is changin the '№' to "No. " with an additional space btween "No. " and the stash-number.

**Comment by LAutour** [comment]
Problem in the truncated user font (would edit the necessary characters in a native font better). In it there is an index on the picture of the character '°', but there is no picture. Therefore, in attempt to output this absent picture of the character, a game takes off.

It is necessary to govern the user font, but not Plugy - is enough to correct one byte in .tbl the file of a font that by a character code '°' to remove 'o'.

And 'No.' is not for all localizations.

**Comment by ChaosMarc** [comment]
I removed the string "N°" completely as it is not applicable to all languages (e. g. in german you would spell "Nr. 1" instead of "No. 1")
