### ISSUE TITLE
How to get Plugy to load with Game.exe?

### ISSUE THREAD

**Issue by mato89** [ChaosMarc/PlugY#56]
I'm using Kolbot so I can only load the game with Game.exe (1.14d).

1) Downloaded PlugY_The_Survival_Kit_v14.03_D2FilePatcher.zip and PlugY_The_Survival_Kit_v14.03.zip
2) Unzipped (1), putting PlugY.exe and dll at the same level as Game.exe.
3) Run PatchD2File.exe

Now when I run Game.exe, I can see PlugY at the bottom right corner. However, PlugY doesn't get loaded when I enter the game. Any idea why?

Other things I tried:
i) Putting PlugY.exe at the same dir as Game.exe was neccessary for PlugY to show at the bottom right coner. Otherwise if I just use PlugY installer it won't show at all.
ii) I tried to use only PatchD2File.exe without the survival kit/ installer as in #48 . In this case no PlugY logo would show up when I launch Game.exe

**Comment by ChaosMarc** [comment]
From what you write I'd say you did everything correctly. What do you mean by "PlugY doesn't get loaded"? No big/multipage stash? this is strange. I've just tested it myself: D2LoD 1.14d + PlugY 14.03 works fine either with PlugY.exe or PatchD2File.exe + Game.exe. All features are loaded ingame. Can you first try it out without kolbot and see if it works? I'm not sure how it injects itself into the game and perhaps the plugy relevant part of the game.exe is not read when kolbot launches the game

**Comment by theBGuy** [comment]
> From what you write I'd say you did everything correctly. What do you mean by "PlugY doesn't get loaded"? No big/multipage stash? this is strange. I've just tested it myself: D2LoD 1.14d + PlugY 14.03 works fine either with PlugY.exe or PatchD2File.exe + Game.exe. All features are loaded ingame. Can you first try it out without kolbot and see if it works? I'm not sure how it injects itself into the game and perhaps the plugy relevant part of the game.exe is not read when kolbot launches the game

I am having issues with this as well, I've installed plugy into the d2 directory. I can launch plugy using Plugy.exe so that part is fine. I ran PatchD2File.exe, but plugy won't load if I try launching using game.exe instead. This is without using kolbot although that is my ultimate goal

**Comment by ChaosMarc** [comment]
Do you get a success message when executing PatchD2File.exe? if yes and plugy is not loaded afterward, please attach the patched game.exe (zip it first)

**Comment by theBGuy** [comment]
> Do you get a success message when executing PatchD2File.exe? if yes and plugy is not loaded afterward, please attach the patched game.exe (zip it first)

I did get a success message after executing PatchD2File.exe, it seems the issue was because the installer created a folder within my diablo directory instead placing the .dll and .ini files at the same level as my game.exe file. I deleted everything then downloaded the zip file and copied the contents over then ran the PatchD2File.exe and now it works

**Comment by ChaosMarc** [comment]
great to hear! closing this now
