### ISSUE TITLE
qol feature request : gold auto pickup

### ISSUE THREAD

**Issue by asrafindp** [ChaosMarc/PlugY#58]
hello
can you add qol feature of gold auto pickup?
it'd be great if this feature can be added to plugy

**Comment by ChaosMarc** [comment]
There is a plugin called BaseMod which offers this functionality which works fine in combination with PlugY. It supports 1.13c, 1.13d and 1.14d. You can find it here: https://www.moddb.com/mods/basemod

**Comment by asrafindp** [comment]
but there are some features in basemod that already exist ini plugy, such as ladder only runeword, diablo clone, uber tristram. does that features conflict with plugy?

**Comment by ChaosMarc** [comment]
you just have to choose one and disable the other. if disabled there are no conflicts

**Comment by asrafindp** [comment]
thank you very much
