### ISSUE TITLE
10.01 needs to be merged into 11.00

### ISSUE THREAD

**Issue by ChaosMarc** [ChaosMarc/PlugY#6]
Yohann's latest release v10.01 brought some nice new features that need to merged in L'Autours v11.00

Perhaps the merge can be performed the other way around to stay closer to Yohann's original code, as it seems that he is active once again

**Comment by LAutour** [comment]
ok. I will add.

**Comment by ChaosMarc** [comment]
@LAutour please wait with your migration efforts. Yohann is still bugfixing his release. A new version will be published soon I think

**Comment by ChaosMarc** [comment]
Yohann did it himself :-)
