### ISSUE TITLE
Feature request - increased rune drop for a Countess

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [ChaosMarc/PlugY#60]
Good day!
I suggest to add configurable increased runedrop for a Countess:
- up to Sol at Normal
- up to Ist at Nightmare
- up to Zod at Hell.

**Comment by ChaosMarc** [comment]
Hey @gandalfthewhite19890404 

sorry for the late reply. This can easily be achieved by txt editing (modding). I would think it would be harder to realize this via code changes than with changing some numbers in the relevant txt files (treasureclass). So I think this is out of scope for this project
