### ISSUE TITLE
Ashen Plains (PD2 with PlugY)

### ISSUE THREAD

**Issue by xijin1337** [ChaosMarc/PlugY#67]
9/10 times when I try to farm on Ashen Plains in Project Diablo 2 the game crashes with:
UNHANDLED EXCEPTION
ACCESS_VIOLATION (c0000005)
When I disable PlugY this error does not occur, PlugY 14.03.
Below is the crashdump file:
[ashen plains - crashdump.zip](https://github.com/ChaosMarc/PlugY/files/11012982/ashen.plains.-.crashdump.zip)

**Comment by ChaosMarc** [comment]
Please inform the Project Diablo 2 developers of this bug. PlugY is not in active development anymore, so I don't think there will be a fix for this anytime soon
