### ISSUE TITLE
Feature request - character titles

### ISSUE THREAD

**Issue by TimothyByrd** [ChaosMarc/PlugY#68]
I really prefer the non-expansion titles (Lord/Lady to King/Queen) to the expansion titles (Slayer to Guardian) is there some way to get those non-expansion titles for expansion characters using PlugY?

**Comment by ChaosMarc** [comment]
I don't think this is something many people would want and it's pretty easy to change by editing D2Win.dll (pre 1.14) or Game.exe (1.14) with a hex editor as the titles can be found in plain text

**Comment by TimothyByrd** [comment]
@ChaosMarc If you could give me some help about editing Game.exe, I'd appreciate it. For example, Game.exe only contains one instance of "Slayer" for an expansion character who has completed Normal, but I would like it to be "Sir" or "Dame" depending on character gender.
