### ISSUE TITLE
Make PlugY compatible with 1.14c

### ISSUE THREAD

**Issue by gmos2104** [ChaosMarc/PlugY#69]
Patch 1.14d just [adds telemetry](https://diablo.fandom.com/wiki/Patch_1.14d_(Diablo_II)) without any bugfix. Since 1.14c is the last patch that added some kind of actual improvement to the game is there any chance to support from this version onwards? I mostly play single player and I find the game calling blizzard servers each time highly undesirable

**Comment by ChaosMarc** [comment]
Adding compatibility to an additional version is a lot of work as you have to find all offsets for all features of PlugY. As the development of PlugY is more or less dead there a no plans for searching those memory adresses. If someone would provide them I would be more than happy to release another version with support for additional versions.

**Comment by gmos2104** [comment]
Hi @ChaosMarc thanks for the reply! I would gladly give it a go myself. I don't have much experience with c++ but I'm willing to give it a go. Is there any instructions somewhere on how to build the mod?

**Comment by ChaosMarc** [comment]
@gmos2104 As far as I remember it should be as easy as checking out the code, opening it with Visual Studio and build the project. It's been a while for me. If you run into problems feel free to open a new issue to get support. The main work of adding compatibility for another patch isn't working with C++ though but finding the right offsets which is done by disassembling the game with e.g. ollydbg with which I cannot help at all :(
